---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 30s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-gitops
  targetNamespace: flask-demo
