---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flask-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-gitops-auth
  url: https://github.com/tyagi-raj/eks-workshop-migration
