apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./gitops/flask-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-gitops
